version: '3'
services:
  postgres:
    image: postgres:9.6
    ports:
      - '5432:5432'
    volumes:
      - database-data:/var/lib/postgresql/data
  web:
    build: .
    environment:
        POSTGRES_USERNAME: postgres
        POSTGRES_HOST: postgres
        POSTGRES_PORT: 5432
    ports:
      - '3001:3000'
    # The sleep command is just to wait for postgres service to start
    command: bash -c "sleep 10; rake db:create; rake db:migrate; rake db:seed; rake assets:precompile && rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - postgres
volumes:
  database-data: null
